### ISSUE TITLE
How do you get get the images to begin with?

### ISSUE THREAD

**Issue by mfekadu** [lint/avg-color-bar#1]
I am mainly asking to know if the frames you sourced were from the HBO stream or from a download (without stream compression) of the Game of Thrones episodes.

Great code by the way! Very readable!

https://www.reddit.com/r/gameofthrones/comments/bju8hs/spoilers_the_average_color_each_frame_of_episode/

**Comment by lint** [comment]
For the GOT videos I got them from thepiratebay.org. I know it really does not help the compression issue but it was the best source I could find.
